name: "TODO.md to GitHub Issue"
description: "Converts todo.md file to GitHub Issues with proper formatting according to agente666 specifications"
author: "agente666"
branding:
  icon: "check-square"
  color: "green"

inputs:
  github-token:
    description: "GitHub token for creating issues"
    required: true
  todo-file-path:
    description: "Path to the todo.md file"
    required: false
    default: "todo.md"
  labels:
    description: "Comma-separated list of labels to add to created issues"
    required: false
    default: "automated,agente666"
  delete-todo-after:
    description: "Whether to delete todo.md file after processing"
    required: false
    default: "true"

outputs:
  issues-created:
    description: "Number of issues created from todo.md"
  issue-urls:
    description: "JSON array of created issue URLs"

runs:
  using: "node20"
  main: "dist/index.js"
